# Generated by Django 5.2.1 on 2025-05-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                (
                    "ISBN",
                    models.CharField(blank=True, max_length=17, null=True, unique=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("year", models.PositiveIntegerField()),
                ("availability", models.BooleanField(default=True)),
            ],
        ),
    ]
